services:
  kafka:
    image: 'neo4j:latest'
    container_name: neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/your_secret_passwd
    volumes:
      - /home/catfish/docker/docker-data/neo4j:/data

