version: '3.8'

services:
  nginx-https-proxy:
    image: nginx:stable-perl
    container_name: nginx-https-proxy
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP端口，用于重定向到HTTPS
      - "443:443"   # HTTPS端口
    volumes:
      # 挂载nginx配置文件
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # 挂载通用代理参数配置
      - ./proxy_params:/etc/nginx/proxy_params:ro
      # 挂载SSL证书目录
      - ./ssl:/etc/nginx/ssl:ro
      # 挂载日志目录（可选）
      - ./logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "https://localhost/nginx-health", "--no-check-certificate"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s