global:
  scrape_interval: 15s

# Target auto-discovery for monitoring containers (including pushgateway)
scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['kafka_exporter:9308']

  - job_name: 'docker'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/*.yml'  # 文件发现目标

# Alertmanager 配置
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'
