services:
  hive4:
    image: apache/hive:3.1.3
    container_name: hive4
    environment:
      - SERVICE_NAME=hiveserver2
    ports:
      - "10000:10000"
      - "10002:10002"
    restart: unless-stopped
