services:
  mysql:
    image: mysql:8.0
    container_name: mysql_01
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: catfish
      MYSQL_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
      - ./logs:/var/log/mysql
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge 