services:
  mysql:
    image: mysql:8.0
    container_name: mysql_01
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: catfish
      MYSQL_PASSWORD: catfish
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_01_data:/var/lib/mysql
      - mysql_01_conf:/etc/mysql/conf.d
      - mysql_01_logs:/var/log/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - mysql_network

volumes:
  mysql_01_data:
    driver: local
  mysql_01_conf:
    driver: local
  mysql_01_logs:
    driver: local

networks:
  mysql_network:
    driver: bridge