services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "19000:9000"  # S3 API 端口
      - "19090:9090"  # MinIO Console Web UI 端口
    environment:
      MINIO_ROOT_USER: admin      # 访问MinIO的用户名
      MINIO_ROOT_PASSWORD: admin123  # 访问MinIO的密码（建议修改）
    volumes:
      - minio_service:/data  # 持久化存储数据
    command: server --console-address ":9090" /data
    restart: unless-stopped
    networks:
      - minio_network

volumes:
  minio_service:
    driver: local

networks:
  minio_network:
    driver: bridge